### ISSUE TITLE
Protótipo de alta fidelidade: Status da denúncia

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#102]
## Descrição da Issue
Fazer o design da telas de status da denúncia, para que possa ser usada na próxima sprint de código. 

### Tasks:
- [x] Criar tela de mudança de status da denúncia

### Critérios de aceitação
- [x] De acordo com o Manual de IDV

**Comment by MatheusBlanco** [comment]
Criei uma tela a mais no protótipo: https://www.figma.com/file/y5ak8SDlqgaPKGfPIble7R/Projeto-Eccoar?node-id=123%3A859

**Comment by Phe0** [comment]
@MatheusBlanco acho q a usabilidade fica melhor sendo só um botão binário. Por exemplo, um botão ou checkbox perguntando, o problema foi concluido? Se não foi concluído ele está em progresso

**Comment by MatheusBlanco** [comment]
> @MatheusBlanco acho q a usabilidade fica melhor sendo só um botão binário. Por exemplo, um botão ou checkbox perguntando, o problema foi concluido? Se não foi concluído ele está em progresso

Arrumei lá, pode revisar novamente?
