### ISSUE TITLE
Cálculo de quantidade de votos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#133]
## Descrição da Issue
Deve-se poder entender qual a porcentagem de votos relativa a quantidade de pessoas existentes em uma localidade, para que  os upvotes possam ter significado.

### Tasks:
- [ ] Realizar pesquisas e estatísticas que mostrem qual a porcentagem ideal de votos em um determinado espaço para que uma denúncia possa ser enviada

### Critérios de aceitação
- [ ] Dados documentados e com base em estatísticas e pesquisas

**Comment by MatheusBlanco** [comment]
https://docs.google.com/document/d/1XNyyUlRmfW0P4hhyy5SEMRSILI2vUtCO8WhCaj4CLtU/edit?usp=sharing

**Comment by MatheusBlanco** [comment]
@devsalula , adicionei a fórmula no documento. Se puder dar uma olhada

**Comment by devsalula** [comment]
Show @MatheusBlanco, manda bala no PR
