### ISSUE TITLE
US14 - Retirada de denúncia

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#153]
**Descrição**
Eu, como cidadão, desejo poder deletar minha denúncia, caso eu sinta que a mesma não foi justificada ou tenha me enganado quanto ao seu teor

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- O usuário deve ser capaz de, na página de detalhamento da denúncia, deletar a mesma e excluí-la permanentemente do banco de dados;
- O usuário deve ser capaz de deletar apenas as denúncias que foram criadas por si mesmo
- Funcionalidade testada;
- De acordo com o protótipo de alta fidelidade;

**Tarefas**
- [x] Criar rota e controller de deleção de denúncia, por id da denúncia e por id do usuário (mandar tanto o id da denúncia quanto o id do usuário, e o id do usuário deve ser igual ao id de usuário existente no objeto de denúncia);
- [x] Criar botão, na página de detalhamento de denúncia, que deve chamar a controller de deleção;
- [x] Tornar o botão renderizável de acordo com uma condicional. Essa condicional deve retornar verdadeiro quando o ID do usuário atual for igual ao id do usuário existente no objeto da denúncia visualizada na página de detalhamento;

**Comment by Victor-Buendia** [comment]
O que já foi feito:

- Criar a rota pra deleção de denúncia;
- Criar controller para deletar a denúncia;
- Criar função que acessa o banco e deleta denúncia;

O que ainda precisa ser feito:

- Testes da controller para deletar denúncia no repo Complaint;
