### ISSUE TITLE
US02 - Autenticação de usuário

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#165]
**Descrição**
Eu, como cidadão, gostaria de poder utilizar minhas credenciais anteriormente criadas para o sistema para que eu possa utilizá-lo em sua totalidade como um usuário pleno.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- O usuário deverá ser capaz de ser autenticado na aplicação com seu e-mail e sua senha;
- O usuário não deverá mais poder utilizar a aplicação (ver denúncias, adicionar voto, criar denúncia) se não estiver autenticado;
- Funcionalidade testada;
- De acordo com o protótipo de alta-fidelidade.

**Tarefas**
- [x] Criar rotas de login e handler de autorização pelo gateway com o firebase;
- [x] Consumir firebase authentication pela rota do gateway;
- [x] Capturar e realizar a validação do bearer token gerado pela firebase;
- [x] Criar a tela de login;
- [x] Salvar as informações de usuário no localstorage (token, userId);
- [x] Renovar o token automaticamente quando ele for expirado;
- [x] Redirecionar o usuário para a tela principal da aplicação;
- [x] Criar proteção de rotas a partir da existência de token e userId na localstorage;
- [x] Desmockar usuários mockados (trocar os campos que estão com userId mockados pelo dado real de userId);
- [x] No banco de complaint, mudar o userId de Number para String
- [x] Arrumar a seed no serviço de complaint 
- [x] HOTFIX - arrumar URL da api para funcionar em produção e em dev, além de retirar consoles do sistema que estão informando dados sensitivos, e trocar a tag do botão da setinha da navbar de imagem para botão

**Comment by Phe0** [comment]
Saleh vai revisar
