### ISSUE TITLE
US18 - Filtro de denúncia por localização

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/2020.2-Eccoar#167]
**Descrição**
 Eu, como cidadão, desejo poder ver apenas as denúncias que estejam perto de mim, para que eu possa identificar os problemas existentes em uma área que eu possa alcançar sem muito esforço ou gasto de recursos.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- O usuário deve ser capaz de ver, no feed de denúncias, apenas aquelas que estejam perto de si, em um raio de 2 quilômetros;
- O usuário deve ser capaz de ser geolocalizado;
- Funcionalidade testada;

**Tarefas**
- [x] Capturar localização do dispositivo
- [x] Criar uma rota no back que pesquisa as complaints pelo raio da localização de latitude e longitude
- [x] Exibir as denúncias que estejam próximas do usuário

_Links de referência_
- https://mariadb.com/kb/en/latitudelongitude-indexing/
- [GeoJSON](https://mariadb.com/resources/blog/mariadb-server-10-2-json-geojson-gis/)

**Comment by Victor-Buendia** [comment]
Referências:
https://developer.mozilla.org/pt-BR/docs/Web/API/Geolocation_API
https://love2dev.com/blog/html-geolocation/
https://whatpwacando.today/

**Comment by Victor-Buendia** [comment]
O back tá funcionando até o momento. Porém a gateway e o front ainda não estão! Depois disspo falta os testes unitários.

**Comment by Victor-Buendia** [comment]
Referência útil: https://github.com/typeorm/typeorm/blob/master/docs/select-query-builder.md#getting-raw-results

**Comment by Phe0** [comment]
@devsalula vai corrigir o PR da complaint
