### ISSUE TITLE
US16 - Feed de denúncias 

### ISSUE THREAD

**Issue by Sabanai104** [fga-eps-mds/2020.2-Eccoar#88]
**Descrição**
Eu, como usuário, desejo poder ver o feed de denúncias, para que eu possa ver as denúncias na página principal do sistema

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Mostrar as denúncias existentes;
- Seguir o prototipo de fidelidade;
- As denúncias devem aparecer ordenadas por data (mais recentes primeiro);

**Tarefas**
- [x] Criar rota e controller para GET no banco de dados;
- [x] Criar a página de feed denúncia;
- [x] Pegar e mostrar no feed as denúncias provenientes do back;
- [x] Paginar a rota de GET;

**Comment by Victor-Buendia** [comment]
Modificações já feitas:

- Criação de nova rota no back /api/complaints
- Criação de um método complaints() na Controller
- Criação de um método getAllComplaints() no Repository
- Paginação do getAllComplaints() com _keys_ **skip** e **take**

Modificações a fazer ainda:

- Conectar com o front os parâmetros da query **skip** e **take**
- Criar limite de paginação com o tamanho do banco de dados **count**

**Comment by Victor-Buendia** [comment]
Novas modificações já feitas:

- Criar a rota no gateway
- Criar proxy da denúncia no gateway
- Criação da página Home.tsx do front redirecionada pelo App.tsx
- Criação da services/api e services/complaints pra gateway
- Criação do estado e efeito na home

Modificações a fazer ainda:

- Conectar com o front os parâmetros da query skip e take
- Criar limite de paginação com o tamanho do banco de dados count
- Criar teste do back
- Mapear os dados do back no front
- Paginar no front as informações no back

**Comment by luiz-herique** [comment]
Novas modificações já feitas:

    Criar a rota no gateway
    Criar proxy da denúncia no gateway
    Criação da página Home.tsx do front redirecionada pelo App.tsx
    Criação da services/api e services/complaints pra gateway
    Criação do estado e efeito na home
    Conectar com o front os parâmetros da query skip e take
    Criar limite de paginação com o tamanho do banco de dados count
    Mapear os dados do back no front

Modificações a fazer ainda:

    Criar teste do back
    Paginar no front as informações no back

**Comment by Victor-Buendia** [comment]
Novas modificações já feitas:

- Criar teste do back

Modificações a fazer ainda:

- Paginar no front as informações no back
