### ISSUE TITLE
US18 - Voto em denúncia

### ISSUE THREAD

**Issue by Sabanai104** [fga-eps-mds/2020.2-Eccoar#91]
**Descrição**
Eu, como cidadão, desejo poder confirmar uma denúncia que eu tenha visto na aplicação, para que ela receba mais visibilidade e relevância a partir de testemunhos

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Rota de contagens de upvote criada;
- A contagem de upvote alterar ao clicar no botão do card do front;
- A informações do upvote esteja vindo proveniente da rota do back e deve ter um feedback visual sobre sua existência;
- Funcionalidade testada padrão;
- De acordo com o protótipo;

**Tarefas**
- [x] Criar um mock do usuário no localstorage, para impedir que um usuário vote mais de uma vez;
- [x] Criar controller para retornar a quantidade de votos em uma denúncia;
- [x] Criação da rota na aplicação que irá guardar informação do novo voto;
- [x] Guardar na tabela de votos o id da denúncia confirmada;
- [x] Fazer um filtro na rota de get de denúncias para retornar as denúncias que foram votadas por usuário;
- [x] Tornar o botão do card clicável, de maneira a criar um campo na tabela de votos das denúncias;
- [x] Conectar com o back o click deu front

**Comment by Victor-Buendia** [comment]
Falta:

- Conectar front e o back
- Teste no back
- Teste no front
